version: '3.8'
services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRESS_PASSWORD: postgres
      MONGO_INITDB_DATABASE: mypass
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/data/db
volumes:
  postgresdata:
    driver: local
