import { Inter } from "next/font/google";
import { Providers } from "@/components/Providers/providers";
import { Header } from '../components/header';

import type { Metadata } from "next";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Библиотека фильмов",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)

{
  return (
    <Providers>
      <html lang="ru">
        <body className={inter.className}>
          <Header />
          <main>
            {children}
          </main>
          {/* <Footer /> */}
        </body>
      </html>
    </Providers>
  );
}

