import { Inter } from "next/font/google";
import { Providers } from "@/components/Providers/providers";
import { NavBar } from "../components/NavBar";

import type { Metadata } from "next";

import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Библиотека фильмов",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>)

{
  return (
    <html lang="ru">
        <body className={`${inter.className} bg-gradient-radial from-sky-400 to-blue-800`}>
        <Providers >
          <NavBar /> 
          <main>
            {children}
          </main>
        </Providers>
        </body>
      </html>
  );
}

